### ISSUE TITLE
提供下载页面

### ISSUE THREAD

**Issue by zozoh** [nutzam/nutzam#1]
在一个目录下，列出所有的文件

```
...
abc.jar
abc.jar.dinfo    
...
```

所有 dinfo 结尾的文件是下载特殊说明文件，这个文件不是必须的。
如果第一次打开下载页面，就会生成。
这个文件本质上就是一个 JSON POJO，映射到数据库里的一个记录

**Comment by pangwu86** [comment]
这个关了吧 好像没啥用了
